# Generated by Django 4.2.5 on 2023-09-22 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='resume.resume'),
        ),
        migrations.AlterField(
            model_name='education',
            name='year_end',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='year_start',
            field=models.DateField(),
        ),
    ]
